name: Runtime-build-test

on:
  push:
    branches:
      - ppc64le_gha
jobs:
  container-create:
    runs-on: ubuntu-24.04-ppc64le
    steps:
      - name: Container
        run: |
          docker stop github-api && docker rm github-api
          docker run -dit --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name github-api ubuntu:22.04
  copy-script:
    runs-on: ubuntu-24.04-ppc64le
    needs: container-create
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy script into container
        run: |
          docker cp $(pwd)/.github/workflows/ppc64le-runtime.sh github-api:/runtime.sh
  runtime-build:
    runs-on: ubuntu-24.04-ppc64le
    needs: copy-script
    steps:
      - name: Run script inside container
        run: docker exec github-api chmod +x /runtime.sh
      - name: Run the script for build
        run: |
          docker exec github-api bash -c "/runtime.sh --build 2>&1 | tee /tmp/runtime-build.log; exit \${PIPESTATUS[0]}"
  runtime-test:
    runs-on: ubuntu-24.04-ppc64le
    needs: runtime-build
    steps:
      - name: Run the script for test
        run: |
          docker exec github-api bash -c "/runtime.sh --test 2>&1 | tee /tmp/runtime-test.log; exit \${PIPESTATUS[0]}"
