name: JIT Testing Pipeline

on:
  workflow_dispatch:

jobs:
  jit-testing:
    runs-on: ubuntu-24.04-ppc64le-p10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Container
        run: |
          docker stop gha && docker rm gha
          docker run -dit --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --network host --name gha ubuntu:22.04
      - name: Copy script
        run: |
          docker cp .github/workflows/jit_testing.sh gha:/jit_testing/
          docker exec gha chmod +x /jit_testing/
      - name: Build
        run: |
          docker exec gha bash -c "/jit_testing"
