name: runtime-build-test

on: #[push]
  push:
    branches:
      - workFlow
jobs:
  container-create:
    runs-on:
      - ashu-runner-self-hosted
    steps:
      - name: Container
        run: |
          docker stop github-api && docker rm github-api
          docker run -dit --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name github-api ubuntu:22.04
  copy-script:
    runs-on:
      - ashu-runner-self-hosted
    needs: container-create
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy script into container
        run: |
          docker cp /root/ashutosh/api/runtime.sh github-api:/runtime.sh
  runtime-build:
    runs-on:
      - ashu-runner-self-hosted
    needs: copy-script
    steps:
      - name: Run script inside container
        run: docker exec github-api chmod +x /runtime.sh
      - name: Run the script for build
        run: |
          # docker exec github-api bash -c "/runtime.sh"
          docker exec github-api bash -c "/runtime.sh --ref workFlow --build 2>&1 | tee /tmp/script.log; exit \${PIPESTATUS[0]}"
          # docker exec github-api chmod +x /runtime.sh
  runtime-test:
    runs-on:
      - ashu-runner-self-hosted
    needs: runtime-build
    steps:
      - name: Run the script for test
        run: |
          docker exec github-api bash -c "/runtime.sh --ref workFlow --test 2>&1 | tee /tmp/script.log; exit \${PIPESTATUS[0]}"
