name: runtime-build-test

on: #[push]
  push:
    branches:
      - workFlow
jobs:
  container-create:
    runs-on: #[self-hosted, ashu-runner-self-hosted]
      - ashu-runner-self-hosted
    steps:
      - name: Container
        run: |
          docker stop github-api && docker rm github-api
          docker run -dit --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name github-api ubuntu:22.04
  copy-script:
    runs-on: #[self-hosted, ashu-runner-self-hosted]
      - ashu-runner-self-hosted
    needs: container-create
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy script into container
        run: |
          docker cp /root/ashutosh/api/runtime.sh github-api:/runtime.sh
  run-script:
    runs-on: #[self-hosted, ashu-runner-self-hosted]
      - ashu-runner-self-hosted
    needs: copy-script
    steps:
      - name: Run script inside container
        run: docker exec github-api chmod +x /runtime.sh
      - name: Run the script
        run: |
          docker exec github-api bash -c "/runtime.sh --ref workFlow 2>&1 | tee /tmp/script.log"
          #docker exec github-api chmod +x /runtime.sh

