name: Sleep for 5 Minutes

on: #[push]
  push:
    branches:
      - workFlow
        #workflow_dispatch:

jobs:
  sleep-job:
    runs-on:
      - self-hosted
      - ashu-runner-self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - name: Container
        run: |
          docker run -it --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name github-api ubuntu:22.04

  copy-script:
    runs-on: 
      - self-hosted
      - ashu-runner-self-hosted
    needs: sleep-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy script into container
        run: |
          docker cp /root/ashutosh/api/runtime.sh github-api:/runtime.sh

  run-script:
    runs-on:
      - self-hosted
      - ashu-runner-self-hosted
    needs: copy-script
    steps:
      - name: Run script inside container
        run: |
          docker exec github-api /runtime.sh --ref workFlow
