name: Sleep for 5 Minutes

on: #[push]
  push:
    branches:
      - workFlow
        #workflow_dispatch:
  
jobs:
  sleep-job:
    #runs-on: 
    # - self-hosted
    # - ashu-runner-self-hosted
    steps:
      - name: Sleep for 1 minutes
        run: |
          echo "hello there!"
          #sleep 60
          #echo "have a good time"
